### ISSUE TITLE
Order of path environment variable. 

### ISSUE THREAD

**Issue by taekyunk** [fpco/minghc#18]
I tried 'minghc-7.8.3' for 64bit version on Windows 8.1.

I noticed that the path for "%APPDATA%\cabal\bin" is added as the last one. Since updated cabal.exe will be installed there when we do `cabal install cabal-install`, I think it might be better to add %APPDATA%\cabal\bin as the first one. If not, windows will always find the old cabal.exe installed in ...\MinGHC-7.8.3\bin\.

**Comment by tejon** [comment]
Just checked on Windows 7. Here, I have fully-qualified `C:\Users\tejon\AppData\Roaming\cabal` in my *user* `PATH` variable, which does indeed get *appended* to the global `PATH` according to `cmd.exe`.

Sadly, a quick test verifies that variables within `PATH` *do not* get expanded, so prepending `%APPDATA%\cabal\bin` to global `PATH` is useless. Of course, putting a fully-qualified user directory in global `PATH` is a non-option. Maybe move *all* the MinGHC path entries to the user variable? I see no other option that doesn't either break something or brush against #17.

**Comment by taekyunk** [comment]
Unfortunately, my description was not clear at all. Actually, you are right that `%APPDATA%\cabal\bin` is fully expanded. I just use %APPDATA% to avoid typing `C:\Users\taekyunk\AppData\Roaming\cabal` since each user will have different user path depending on his/her username. It is not the problem that I am reporting. 

At least in Win 8.1, minghc adds GHC related PATH variables in user variables for `PATH` instead of global `PATH`. So, as long as minGHC shuffles the PATH segments so that the first element is `C:\Users\<username>\AppData\Roaming\cabal`, an updated cabal.exe will be available to users without a problem.

**Comment by ndmitchell** [comment]
It's not a simple problem to solve. The user is more than likely to have an out-of-date `cabal` in their `%APPDATA%` before installing MinGHC, so we want the latest one we ship to take precedence. Of course, if the user does `cabal install cabal-install` we want that version to take precedence. Unfortunately there's no way to do that with the `%PATH%`, and on the assumption `cabal` changes rarely, our approach isn't bad (in practice, `cabal` has changed 4 times in the last week, so either it's not a good assumption, or it's not a good assumption over the festive period).

We always write to the user `%PATH%` because that's safer, and doesn't require admin access, and is always able to uninstall from. As @taekyunk says, I don't think that's a relevant factor here.

Nice catch on not expanding though, that should be easy to fix.

**Comment by tejon** [comment]
Stackage LTS is still using a 1.18 version of `cabal`. Assuming that's for a good reason and not simply an oversight, the current path situation could actually be giving too *new* a version! For my two cents, I'd prefer to see an up-front warning for the user to be aware of where old versions can hide, and the path set to favor `%APPDATA%\cabal\bin`.

> We always write to the user `%PATH%`

I guess this is an unrelated issue, but for me everything *except* `%APPDATA%\cabal\bin` went in my global path, NOT user. I know this isn't an artifact from previous Haskell installations because I just reinstalled Windows fresh last week, and haven't installed any other Haskell since!

**Comment by taekyunk** [comment]
Then, how about this approach?

When installing minghc,
1. set `C:\Users\<username>\AppData\Roaming\cabal` as the first element of minghc related path in user `PATH`. 
2. run `cabal update` and `cabal install cabal-install` before finishing installation

If this is possible, users will have up-to-date cabal in `%APPDATA%` and there will be no need to shuffle `PATH` variable when users update `cabal` again in the future.

**Comment by ndmitchell** [comment]
Running `cabal install cabal-install` can take quite a while, so I wouldn't want to do that at installation time.

One potential option would be to detect if they have a `cabal.exe` in `%APPDATA%`, and if it is older than our one, offer to overwrite it. If we do that, putting the `%APPDATA%` first in the `%PATH%` wouldn't be a problem. Requires a bit of nasty to parse the `cabal.exe` version string, but should be feasible.

**Comment by taekyunk** [comment]
> One potential option would be to detect if they have a cabal.exe in `%APPDATA%`, and if it is older than our one, offer to overwrite it. If we do that, putting the `%APPDATA%` first in the %PATH% wouldn't be a problem.

This sounds like a really good plan. It will keep cabal up-to-date upon installation and `%PATH%` will be set up to work when `cabal` is updated in the future.

**Comment by snoyberg** [comment]
I like @ndmitchell's plan too. I think the best approach is to write a minimal Haskell program to do this check, bundle it with MinGHC, and run it automatically from the nsis installer. If anyone has an objection to that plan, please say so now.

**Comment by varosi** [comment]
+1

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported. Stack is in many ways the program that does the check, but instead of just doing the check, it also sets the path too - even better.
