### ISSUE TITLE
Better story for admin vs non-admin

### ISSUE THREAD

**Issue by conklech** [fpco/minghc#2]
At least on Windows 8, installing to the default directory, under "C:\Program Files (x86)\", fails with "Error opening file for writing." This is presumably because the installer hasn't sought UAC elevation, and that location is not writable with user permissions.

**Comment by 3noch** [comment]
We still have work do to here. The installer requires elevated privs immediately on startup and once running the default paths will belong to the admin user, not the user who is running the installer! @ndmitchell Any ideas how to solve this?

**Comment by 3noch** [comment]
Worse of all, the `PATH` of the admin user will be changed instead of the user running the installer.

**Comment by ndmitchell** [comment]
I think if the installer is run as admin, it should do an admin install, if not, it should do a user install. I guess that means it needs to detect if it has admin privileges in advance - not sure how you do that in NSIS - will probably require some plugin.

**Comment by 3noch** [comment]
Given my discovery of #60, I'm wondering whether our hopes of not requiring admin are lost. Even if we could get an installer that properly installed on non-admin accounts, the `network` library would not build. I'm guessing #60 is actually a bug of some sort, but at least for now, there's little encouragement to make MinGHC friendlier to non-admins.

The trouble however that we face is that since the installation is 100% user-local, when a non-admin get's admin permissions, he ends up installing MinGHC for someone else entirely, instead of installing something system-wide as he'd expect.

**Comment by ndmitchell** [comment]
I am using MinGHC on a non-admin account - it does work, you just have to adjust the installation directory and ignore the prompt to increase privileges. With that, it does work.

**Comment by 3noch** [comment]
Hmmm. I couldn't figure out how to ignore the admin-login prompt.

**Comment by 3noch** [comment]
See #67

**Comment by ndmitchell** [comment]
So I used to be able to ignore the admin-login prompt, but I can't anymore, which explains the discrepancy.

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported.
