### ISSUE TITLE
Use MSYS2 instead of MSYS1

### ISSUE THREAD

**Issue by mantkiew** [fpco/minghc#20]
MSYS2 is recommended on both [Haskell Wiki](https://www.haskell.org/haskellwiki/Windows) and [GHC Wiki](https://ghc.haskell.org/trac/ghc/wiki/Building/Preparation/Windows).

**Comment by ndmitchell** [comment]
Given MSYS1 works, I don't think installing MSYS2 is going to offer any significant advantages. It's newer, so a good reason to upgrade at some point, but these things are very hard to test they don't make some obscure bit worse.

The reason it's recommended on the GHC wiki is because it's faster and better for compiling GHC itself - if MinGHC was capable of easily compiling GHC itself that would be a compelling reason to have MinGHC ship MSYS2. I'm going to get a new GHC compiling machine shortly, so might take a look then.

**Comment by mantkiew** [comment]
In my experience, MSYS2 just works as a replacement. The big advantage is pacman for package management. There are problems with updates though, when the machine needs to be restarted to unload the dll... It would be great to be able to compiler GHC with minghc, it would significantly lower the barrier for many people.

**Comment by elieux** [comment]
Sorry for hijacking this thread, but is there a document/page describing how your distributions differ from just downloading MSYS and GHC? I'm in the process of making a GHC package for MSYS2 and I'd be glad if I we could combine our experiences to make it work well.

> There are problems with updates though, when the machine needs to be restarted to unload the dll...

When/how has this happened? I've never had to do this. I'm genuinely interested in this, because such situations could be a big problem for us and our users.

**Comment by ndmitchell** [comment]
Hi @elieux - our package is basically downloading both, shoving in the same installer. We don't do anything clever.

**Comment by mantkiew** [comment]
@elieux please refer to the [MSYS2 installation & update instructions](http://sourceforge.net/p/msys2/wiki/MSYS2%20installation/). In `III. Updating packages`, they explain how it differs with the original update behavior on ArchLinux.

**Comment by mantkiew** [comment]
Finally, I would like to add that since MSYS2 is being recommended on the official Haskell websites, many people are using it (I presume). Getting MSYS1 in MinGHC is certainly an inconvenience for them and myself. I have Makefiles and other scripts that rely on the ability to install basic packages such as `zip`, `wget`, etc. using pacman. When I get MinGHC, I'll rip MSYS1 off and continue using MSYS2.

**Comment by ndmitchell** [comment]
Patches welcome :). I don't have any time to invest at the moment and MinGHC, so don't have any intention of doing anything significant in the next month or so. Alternatively, I will eventually get to the issues and try and sort some of them out.

**Comment by elieux** [comment]
@mantkiew, there's no mention of needing to restart your machine. The only clumsy thing that is sometimes needed, is to close all running MSYS2 windows and processes.

> I don't have any time to invest at the moment and MinGHC

Hopefully, I'll get the MSYS2 package working soon(-ish) and that should satisfy some of the people who'd like to get GHC on MSYS2.

**Comment by 3noch** [comment]
We're now piggybacking off of MSYS2 that comes with Git.
