### ISSUE TITLE
can't install 64 bit build on window

### ISSUE THREAD

**Issue by cartazio** [fpco/minghc#22]
seeing messages like 
```
error opening file for writing
C;\Program Files\MinGHC-7.8.4\bin\alex.exe
```
etc, for all the various bins in the installer. This is also on a pretty locked down windows box

**Comment by cartazio** [comment]
it looks like the windows installer requires admin priveleges for some reason

**Comment by ndmitchell** [comment]
Writing to `Program Files` requires admin privileges so there is no way around that. We can certainly do better to detect you are lacking admin, and default to a directory you can write to - we have a ticket for that as #2. In the meantime, if you rerun the installer and select an alternative directory, one inside My Documents, you should have more success (we deliberately write to the user copy of `%PATH%` so that shouldn't trip you up).

**Comment by cartazio** [comment]
that seems to be working (or seemingly so), thanks!
