### ISSUE TITLE
Optional packages for MinGHC?

### ISSUE THREAD

**Issue by Kludgy** [fpco/minghc#25]
Thanks for this installer. Really makes my life on Windows a lot more pleasant.

Just wondering if owner/users would be interested PRs for tricky package installs for say, GTK2/3 and SDL? Seem to be common sore points.

Cheers.

**Comment by ndmitchell** [comment]
My thoughts are that as long as that don't make the distribution that much bigger, shoving other things in can only help. @snoyberg, thoughts?

**Comment by Kludgy** [comment]
I was thinking the same. One of my questions here is whether some larger, optional pieces should be downloaded and installed on demand. (Noting the irony of reinventing yet another package manager.)

**Comment by ndmitchell** [comment]
Hmm... Becoming a download manager isn't a good plan, generally speaking, since that adds a lot of complexity that I don't want. What about having a cabal package "install-gtk2hs" so a user can do `cabal install gtk2hs && gtk2hs-install` to get the system set up for them? You can't do that with MinGHC because the standard GHC lacks network and Cabal, but once you have MinGHC there are more options.

**Comment by Kludgy** [comment]
Yea GTK is a pretty hefty dependency.

But off the top of my head, building on top of MinGHC, a `cabal install gtk2hs` would have to:
* Obtain/move GTK dev files somewhere visible to the environment.
* Sensibly extend PATH to the `bin` deps. (`pkg-config.exe` should come along with this.)
* Extend the PKG_CONFIG_PATH.
* Rebuild `alex` and `happy` for additional artifacts that `gtk2hs-install` can find. (Can we just include these with MinGHC perhaps, or are the artifacts machine dependent? Haven't looked into this yet.)

**Comment by tejon** [comment]
GTK is big, but useful for a lot of things (not least `pkg-config`). But it's also a trivial install once you find the right package. Unpacking `gtk+-bundle-3.6.4-20130921_win32.zip` directly into `msys-1.0.1\` puts everything where it needs to be.

The current SDL2 development package for Windows installs itself correctly with `make native` from msys, but contains a bad include header which breaks `cabal-install sdl2`; there's a drop-in fix, but of course it takes a bit of effort to find the solution; [it's here](https://hg.libsdl.org/SDL/raw-file/e217ed463f25/include/SDL_platform.h), and goes into `msys-1.0.1/include/SDL2`.

I have yet to get the `SDL` package (SDL1, required for e.g. `helm`) to install. The mingw32-specific development package doesn't include a pgk-config .pc file. Building it from source does; but that installs everything to `/usr/local`, which msys doesn't really use. Moving it out is easy enough of course, and there *appears* to be only one edit necessary to `sdl.pc` at that point (`prefix=/usr/local' -> 'prefix=/usr'), but `cabal install sdl` still fails with `Missing C library: SDL` -- so this one's definitely sticky.

GLUT and GLFW, required for `gloss`, both have similar tangles. I haven't even tried with those yet.

**Comment by Kludgy** [comment]
@tejon Would you be willing to try the Helm build from source for x86-64? I only install from dev bins. SDL2 addresses the pkg-config deficiencies in case SDL is too much of a nuisance to support. And yay, Helm uses SDL2 since Nov 2013 as well.

**Comment by tejon** [comment]
My experiences thus far with x64 have led to me no longer being willing to try anything with x64. ;)

You're quite right about Helm using SDL2 now, so perhaps SDL1 can be safely ignored. I don't think anything else of note uses it.

**Comment by ndmitchell** [comment]
@snoyberg @3noch - we probably need a "story" to tell here. As a recent example, @deech on Twitter asked about supporting https://github.com/deech/fltkhs out of the box. My thoughts:

* We can't ship every package ever in the default install. We have to draw the line somewhere. None of these libraries are insanely popular, so the natural place to draw the line is at including none. Perhaps OpenGL and hmatrix would be another place to draw the line.
* It would be nice if the users would get it working with MinGHC. That requires downloading it and putting it somewhere "expected". Since we want the flexibility to do that generically, we either need a database of custom rules for common packages, or the packages to tell us what they require.
* You really want the package to do that as part of its setup, e.g. during `cabal install`.

My eventual conclusion is that `stack` or `cabal` should take care of setting these packages up, and not MinGHC. @snoyberg, does this sound in scope for `stack`? If so, something like `hmatrix` is a nice simple test case - plus my wife uses it so it would make it easier to get computers up and running for her.

**Comment by deech** [comment]
If it helps you decide, fltkhs (http://hackage.haskell.org/package/fltkhs) is far from standard, but it is a one dependency GUI binding ( that dependency being the C++ library it binds to ) that works smoothly with the latest MinGHC (http://hackage.haskell.org/package/fltkhs-0.1.0.2/docs/Graphics-UI-FLTK-LowLevel-FLTKHS.html#g:4). It is much easier to install than gtk2hs on all platforms. 

So maybe it isn't a great candidate for bundling since the user can install it by themselves without too much hassle.

**Comment by tejon** [comment]
FWIW, `fltk` is also among the packages provided via `pacman` in the full version of MSYS2. (ref. #63)

While @ndmitchell's suggestion of handling binary dependencies via `stack` or `cabal` is attractive from a convenience standpoint, I also think the proliferation of different ways to do the same thing is causing a lot of harm. There's a working solution with a lot of support behind it which covers the entire gnu-toolchain ecosystem rather than just Haskell. Even if we do wind up with convenient self-contained `cabal` installation at some point, this seems like the right platform to build from just from an interoperability standpoint.

**Comment by snoyberg** [comment]
I like the idea of using some kind of an external package management tool (like MSYS2, possibly *actually* MSYS2). I could picture `stack` developing this logic in the future if necessary, but shipping the libraries with MinGHC does in fact seem out of scope.

So as I see it, the goal should be "have an easy way to get extra libraries once you've installed MinGHC." Whether that's pacman or something else is a great "next step" discussion, but we should agree on this as the first step before moving forward with that latter discussion.

**Comment by 3noch** [comment]
This might be a pipe dream of mine, but I very much prefer the idea of teaching cabal how to install everything necessary for a library to work. That might even mean having several *wrapper* packages which merely bundle up a binary for a specific platform and then an umbrella package which conditionally depends on the right binary. I dislike global dependencies very much since they completely break referential transparency!

**Comment by deech** [comment]
Doesn't the Cabal API allow this? Granted this isn't supported by the Cabal file, but to my understanding nothing's stopping the library/app developer from building this into their `Setup.hs`.

That said at least with foreign libraries I don't know this is a good approach. This would circumvent package managers and take control away from devops. In enterprise setting that might be frowned upon.

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported. I suggest taking GTK etc additional libraries to the Stack tracker, where there has been work to integrate Nix for such things.
