### ISSUE TITLE
Code-sign installers

### ISSUE THREAD

**Issue by 3noch** [fpco/minghc#61]
The experience is yucky because we don't have signatures for our installers. Let's look into it.

**Comment by 3noch** [comment]
[Certum](http://certum.eu/certum/cert,offer_code_signing.xml) will do code signing for free for open-source projects.

**Comment by 3noch** [comment]
I just signed up to receive a free certificate. We'll see how far I can get...

**Comment by 3noch** [comment]
@snoyberg It's not too bad. However, the "real deal" uses physical dongles to verify identity of the signer. But there are less secure versions. You can use Windows [sign tool](https://msdn.microsoft.com/en-us/library/windows/desktop/aa387764(v=vs.85).aspx) and a certificate from somewhere like Symantec.

https://msdn.microsoft.com/en-us/library/ms537361(v=vs.85).aspx

**Comment by 3noch** [comment]
Automating the process has been a real pain for my team because of the physical dongle and certain permissions rules. Doing it by hand on the command-line is quite easy, however. You just need a certificate and an authority and `signtool.exe` will do all the work.

**Comment by snoyberg** [comment]
I'd already asked @borsboom, who's the release manager for stack, to look into automatically building a new MinGHC release together with each stack release (so that MinGHC's copy of stack doesn't fall out of date). Perhaps we can include in that process usage of `signtool.exe`. Going farther: maybe it's worth signing the stack.exe executable as well.

**Comment by 3noch** [comment]
Windows do love them a good signature.

**Comment by borsboom** [comment]
@3noch, @snoyberg : I've created a draft release at https://github.com/fpco/minghc/releases/tag/untagged-4ad38a4cde212186de53, which has signed installers (and the `stack.exe` they install is also signed).  Since this is my first attempt at building MinGHC, can you please sanity check them before I include them in the stack-0.1.5.0 release announcement?

**Comment by 3noch** [comment]
@borsboom Great work! I can see that the 64-bit 7.10.2 installer is signed, but the Timestamp says "Not available." Windows 10 SmartScreen is still discouraging me from running it. :(

**Comment by borsboom** [comment]
@3noch: I've uploaded a new 64-bit 7.10.2 installer with a timestamp, give it a try!

**Comment by 3noch** [comment]
@borsboom Nice! The time stamp is there now. Windows SmartScreen still warns me. I have no idea what to do about that.

**Comment by 3noch** [comment]
Looks like `stack.exe` is signed too. I only tested 7.10.2 64-bit. If you have a signing script, you might want to just sign all `exe`s that we install. Just an idea. I don't know how much good it would do.

**Comment by borsboom** [comment]
I'm not finding any authoritative information through googling, but what I gather from a few different places is that having a signature won't automatically bypass SmartScreen.  That will go away once enough people download it and who don't flag it as malicious.  It also sounds like some extended validation certificates from specific CAs (Symantec and DigiCert wre mentioned) may, over time, become trusted so that all executables signed with those certificates don't get the warning by default.  *shrug*, doesn't seem like it's worth paying the big bucks for an EV certificate in the hopes that it might help eventually.  At least Windows doesn't make it especially difficult to bypass (it's actually less annoying than OS X's defaults).

Still worth signing, just so that "FP Complete" does at least appear.

**Comment by snoyberg** [comment]
Thanks @borsboom, closing as implemented.
