### ISSUE TITLE
Request variant of MinGHC for users already having MSYS2/MINGW installed

### ISSUE THREAD

**Issue by asampal** [fpco/minghc#65]
It would be nice to not have redundant installations around if I've already got MSYS2/MINGW set up nicely.

**Comment by tejon** [comment]
Agreed, especially because with MSYS2 we're not just talking about extra files, but shared non-Haskell libraries.

Since both git4win and MSYS2 register themselves with Windows, I think the optimal solution would be to detect them from the MinGHC installer, and (by default) only install them if not present. Simpler but still effective would be checkboxes for "use existing MSYS" and "use existing Git For Windows" which would request the location of a current installation, and use that.

ref #63

**Comment by 3noch** [comment]
Perhaps we should merely point users directly to GHC download links for this use case. There is really little left to do if you already have MSYS. I wonder if people think it is harder than it is.

**Comment by tejon** [comment]
The last time I tried MSYS2 (about 10 months ago?) it was a slow and convoluted install, and when I aborted it midway once because I realized I'd misunderstood one of the options, it managed to delete *every shortcut on my computer*. So yeah, I wouldn't be surprised if a lot of people still think, based on reports or experience, that it's harder than it actually is now.

That said, there's still some convenience to be gained from MinGHC, if only in that it's so much easier to *find* correctly matching versions of GHC and Cabal when they're bundled here. My current set-up was:

- install MSYS2;

- install Git4Win;

- open MinGHC installer in 7zip, unpack GHC to a root folder and Cabal.exe to hand-created `%APPDATA%\cabal\bin`, add `PATH` entries for both.

I was very happy to have that installer for part 3, despite not using it remotely as intended. :) An option that does only the work I did by hand would be welcome, and having the relevant bits live in the MinGHC directory structure wouldn't hurt anything (whereas for MSYS2 and G4W, it kind of does).

**Comment by 3noch** [comment]
Good thoughts. I am curious what *target audience* we're aiming for with MinGHC. I think some of these issues would be cleared up if the audience were well defined. To me, anyone who is going to do a lot with foreign libs in Haskell is likely also skilled enough to install MSYS, GHC, and Cabal by hand. I might be wrong. I also see MinGHC as a targeting the same folks as Haskell Platform did/does. For some reason, I often don't consider either audience to be heavy-duty use cases. If you need specialized setups, you almost always have to do more work yourself, even on Linux.

I say this mainly to get it on the table, not to argue my perspective.

**Comment by tejon** [comment]
I definitely think priority should be given to new users who don't know anything about the toolchain. Lower the barrier to entry, let them start playing with the examples they've found online ASAP. But I also think the idea that this has to come at the expense of making it less useful for more advanced users is a false dilemma. In fact, clearing rubble from the path to *becoming* a more advanced user seems like the right goal.

I know I certainly would have had a quicker and more engaged start with Haskell if it hadn't been so hard to get any graphics libraries working that I kept going back to Unity just so I could make something happen on screen.

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported. I think Stack requires everything installed themselves, but you can always ask them.
