### ISSUE TITLE
Allow to install via a script

### ISSUE THREAD

**Issue by nkaretnikov** [fpco/minghc#86]
It would be neat if the installer didn't require human interaction (that is, pressing the "Next" button), so I could use it in a script.

I'm no expert on Windows, but (IIUC) it's usually done by making an installer accept command line options.

**Comment by ndmitchell** [comment]
This already works since we have an NSIS installer, and the standard command line flags work - for example `/S` installs silently. I don't have a complete reference, and can't find one now, but it's already supported. Let me know if you can't figure out the command lines (I'd guess at `/S` and the install directory).

Alternatively, you can use stack, and something like `stack setup --install-ghc` (at a guess, I've seen the command line, but can't remember it).

**Comment by nkaretnikov** [comment]
Good to know.  I tried /h or something like that, but it didn't return
anything.  I'll take a look and report back.

**Comment by nkaretnikov** [comment]
Okay, this seems to work:
http://nsis.sourceforge.net/Docs/Chapter4.html#silent

Is there a way to support a help option?

**Comment by ndmitchell** [comment]
That seems like something that would be best baked into NSIS itself, although it does appear to be lacking. I can't even find a good reference on what flags are supported by NSIS, since then we could link to that.

**Comment by nkaretnikov** [comment]
Not a blocker for me, so feel free to close this issue.

**Comment by ndmitchell** [comment]
I think our official advice is probably if you want command line, use stack which is going to be easier. But /S works too.
