### ISSUE TITLE
Include glut32 library

### ISSUE THREAD

**Issue by mwu-tow** [fpco/minghc#90]
I'd like to ask you to consider including glut32 C library to MinGHC distribution.

I saw a similar request that was rejected (#37) stating that you are rather not going include libraries, so I'll understand if you decline that. Still, I believe that is case is somewhat special and deserves some attention.

The glut32 library is needed for a quite a few Haskell packages, like `gloss` and sometimes is used tutorials that aim to show how easy it is to draw something on screen with Haskell. 

The problem is that it is non-trivial to obtain this library on Windows. The user receives an error about missing `glut32` C library. When I searched for it, I ended on webpage that apparently was not updated for the last 15 years and doesn't contain x64 binaries.

The solution is to download `freeglut` library binaries, then to rename its .a files from `libfreeglut` to `libglut32` and put in the proper place. It is non-obvious for many users that a `freeglut` is binary compatible with `glut32` and that it can be used in its place if renamed.

I guess that for similar reasons Haskell Platform decided to include this library (AFAIK it is the only C library they distribute). I believe that having it distributed with MinGHC would be helpful to many users, as obtaining this library on Windows is kind of problematic. Certainly it will be convenient for me.

Still, it is your call whether it fits the policy of the project.

**Comment by ndmitchell** [comment]
The options are either to ship it as standard (which is a bit yuk), or have `stack` gain the smarts so that it could install the library, perhaps by stack having a custom "on windows to get glut32 script" inside it. I suspect, given the way the projects are going, you're far more likely to have success with `stack`. Having `stack` be able to install everything the Haskell Platform has seems like a sensible goal, if it wants to be considered as a platform replacement.

**Comment by snoyberg** [comment]
I'd say the best first step is to get the process well documented, and then
scripted. Once that happens, we can decide if we want to include it in
minghc/stack. But either way that step will be useful.

**Comment by 3noch** [comment]
It seems to me that it should be theoretically possible for the `Cabal` library to represent complex installs like this. I'm not sure if it can do so currently, but I have wanted to build cross-platform libraries that "just work" by having them embed complex dependencies, like pre-built C libraries.

**Comment by snoyberg** [comment]
My hope is that by moving to MSYS2/pacman, installing C libraries can
become much easier on Windows. I actually tweeted about one such experience
recently: https://twitter.com/snoyberg/status/638359459304239104

**Comment by mwu-tow** [comment]
You raised a good point — if the tools can install C libraries for the user, then distributing them won't be necessary. And adding more libraries would be much easier (I just had some trouble installing `pcre`, the problem is not `glut32`-specific).

Teaching `stack` (or Cabal) to fetch the dependencies would be probably the best solution. If Msys2 can serve that purpose — that's great, as long as user does not need to know about it.

Things to note here:
* often the `.dll` name is different from the name of its corresponding import library `.lib`. In such case `ghci` is unable to load such `.dll`. The fix is to create to copies of `.dll` file — one named for ghci, one for system loader.
This can be elegantly solved by using `extra-ghci-libraries` — if the dll names are passed to ghci, file renaming is not necessary.
* developer wants to have both 32 and 64-bit binaries installed — and getting appropriately picked depending on current build target
* the problem is often in `configure` scripts. Well, using them on Windows is just asking for trouble. Ideally `Cabal` library should provide an equivalent functionality and running custom configure steps should be realized in `Setup.hs`. I believe that if `Cabal` provided a few simple functions, a vast majority of `configure` scripts could be removed and the whole Msys trickery wouldn't be necessary. (it is necessary at the time but it would be really great if some better alternative would be offered to developers)

**Comment by 3noch** [comment]
Has anyone ever considered creating mirror packages of C libraries **within hackage**? So if a library needs `pcre`, for example, it would declare a native Cabal dependency instead of relying on the user to link in some 3rd-party? Cross-platform packages could be achieved with having different mirror packages for each supported system and using conditional dependencies in Cabal to pull down the right one. The downside would be for devs who need some custom build of the 3rd-party, but I imagine that it would be easy to provide mechanisms for overriding paths, etc. Still, in the average case, this would make doing cross-platform dev in Haskell quite painless.

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported. I think Stack and Nix can play well together, to some extent, but it's certainly an interesting question.
